/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/buttons/Button.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    Input: typeof import('./../components/input/input.vue')['default']
  }
}
